app/article_03/models.py
import os

from flask import request, redirect
from app import app


def allowed_file_types(filename):
    if not "." in filename:
        return False

    extension = filename.rsplit(".", 1)[1]

    if extension.upper() in app.config["ALLOWED_IMAGE_EXTENSIONS"]:
        return True
    else:
        return False


def upload_file(uploaded_file):
	uploaded_file = uploaded_file

	if uploaded_file.filename == "":
		print("No filename")
		return redirect(request.url)
		
	if allowed_file_types(uploaded_file.filename):
		uploaded_file.save(os.path.join(app.config["UPLOAD_FILES"], uploaded_file.filename))
		return redirect(request.url)
	else:
		print("That file extension is not allowed")
		return redirect(request.url)

app/__init__.py
from flask import Flask

# app config
app = Flask(__name__)
app.config.from_object("configuration.DevelopmentConfig")

# import routers
from app import routes_website

# register blueprints
from app.article_01.views import article_01_blueprint
from app.article_02.views import article_02_blueprint
from app.article_03.views import article_03_blueprint

app.register_blueprint(article_01_blueprint, url_prefix='/article-01')
app.register_blueprint(article_02_blueprint, url_prefix='/article-02')
app.register_blueprint(article_03_blueprint, url_prefix='/article-03')

app/article_01/views.py
from flask import render_template, Blueprint


article_01_blueprint = Blueprint("article_01", __name__, template_folder='templates')


@article_01_blueprint.route('/welcome')
def welcome():
	return render_template("article_01/welcome.html")


@article_01_blueprint.route('/chapter-01')
def chapter_01():
	return render_template("article_01/chapter-01.html")


@article_01_blueprint.route('/resource')
def resource():
	return render_template("article_01/resource.html")

app/article_02/views.py
import json
from flask import Blueprint, render_template, request, redirect


article_02_blueprint = Blueprint("article_02", __name__, template_folder='templates')


with article_02_blueprint.open_resource("./templates/article-02/data.json", "r" ) as data_file:
		data = json.load(data_file)


@article_02_blueprint.route('/welcome')
def welcome():
	return render_template("article-02/welcome.html", **data)


@article_02_blueprint.route('/chapter-01')
def chapter_01():
	return render_template("article-02/chapter-01.html", **data)


@article_02_blueprint.route('/resource', methods=["GET", "POST"])
def resource():

	if request.method == "POST":
		first_name = request.form.get("first_name")
		last_name = request.form.get("last_name")

		with open("./templates/form_data.json", "w") as form_data_file:
			form_data_file.write(first_name + "\n")
			form_data_file.write(last_name + "\n")

		return redirect(request.url)

	return render_template("article-02/resource.html", **data)

app/article_03/__init__.py
# No content
# We need this file just to make this folder a python module

app/article_03/views.py
from flask import render_template, Blueprint, request
from app import app

from app.article_03.models import *

article_03_blueprint = Blueprint("article_03", __name__, template_folder='templates')

@article_03_blueprint.route('/welcome')
def welcome():
	return render_template("/article-03/welcome.html")


@article_03_blueprint.route('/chapter-01', methods=["GET", "POST"])
def chapter_01():
	if request.method  == "POST":
		if request.files:
			upload_file(request.files["upload-form"])

	return render_template("/article-03/chapter-01.html")


@article_03_blueprint.route('/resource')
def resource():
	return render_template("/article-03/resource.html")

app/templates/article-01/welcome.html
{% extends "templates/article-template.html" %}

{% block page %}
<section>
	<img src="https://images.unsplash.com/photo-1461711513774-c78b437a740b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=1600" alt="random picture">
</section>

<section class="page-header">
	<h1>Python Web Scraper</h1>
	<div class="overline">Category: Series</div>

	<p class="objective-paragraph">Welcome! The <strong>objective</strong> of this tutorial is to build web scraper that creates a YouTube playlist based on songs in your Shazam library</p>
</section>

<div class="card card--course util-margin-top-30">
	<div class="card__title">
		<div class="card__title--main">Chapter One</div>
	</div>
	<div class="card__content">
		<p>Set up project folder and write the code that crawls through your Shazam libray.</p>
	</div>

	<div class="card__button">
		<div class="button">
			<a href="{{ url_for('article_01_chapter_01') }}">go to chapter</a>
		</div>
	</div>
</div>

<div class="card--course__connector">
	<div></div>
	<div></div>
</div>

<div class="card card--course">
	<div class="card__title">
		<div class="card__title--main">Chapter Two</div>
	</div>
	<div class="card__content">
		<p>Set your YouTube account to accept incoming data and create or add songs to a specified playlist.</p>
	</div>
	<div class="card__button">
		<div class="button">
			<a href="#">go to chapter</a>
		</div>
	</div>
</div>

<div class="card--course__connector">
	<div></div>
	<div></div>
</div>

<div class="card card--course card--course__success">
	<div class="card__title">
		<div class="card__title--main h1">Complete</div>
	</div>
</div>

<hr />
<h2 id="conclusion">Course Updates</h2>
<table class="util-margin-bottom-60">
	<tr>
		<th>Date</th>
		<th>Description</th>
	</tr>
	<tr>
		<td>03/22/2016</td>
		<td>
			<ul>
				<li>Upgraded to Python version 3.5.1</li>
				<li>Added autoenv version 1.0.0</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td>02/22/2015</td>
		<td>Added Python 3 support</td>
	</tr>
</table>
{% endblock %}

app/templates/article-03/chapter-01.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for( navigation.welcome_link ) }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( chapters[0].chapter_link ) }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( navigation.resource_link ) }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<section class="page-header">
	<h1>Step {{ chapters[0].number }}</h1>
	<div class="overline">{{ title }}</div>

	<p class="objective-paragraph">Welcome! The <strong>objective</strong> of this tutorial you will learn to import JSON as data, unpackage the data, and populate the view template with such data.</p>
</section>

<section>
	<div class="card util-margin-bottom-60">
		<div class="card__title">
			<i class="material-icons md-36">flag</i>
			<div class="card__title--main">In This Article</div>
		</div>

		<div class="card__content">
			<p>Even though we'll go through the following topics, you may not find what you need. If that's the case, please review the sources's documentation below for more information.</p>

			<ul>
				<li class="inine-list">JSON Module -
					<a class="straight-link" href="https://docs.python.org/3/library/json.html">
						Learn More
						<i class="material-icons md-18">open_in_new</i>
					</a>
				</li>
				<li class="inine-list">*args and **kwargs -
					<a class="straight-link" href="https://book.pythontips.com/en/latest/args_and_kwargs.html">
						Learn More
						<i class="material-icons md-18">open_in_new</i>
					</a>
				</li>
				<li class="inine-list">app.get_resource() -
					<a class="straight-link" href="https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.open_resource">
						Learn More
						<i class="material-icons md-18">open_in_new</i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>

<section class="table-of-contents">
	<h2 class="table-of-contents__title">Table of Contents</h2>
	<ul>
		{% for header in step_one.article_headers %}
		<li>
			<a href="{{ url_for( chapters[0].chapter_link )}}#{{ header.link }}">{{ header.header }}</a>
		</li>
		{% endfor %}
	</ul>
</section>

<section class="callout-section util-padding-vert-50">
	<div class="callout callout__content callout_get_code">
		<i class="material-icons">
			code
		</i>
		<p>Need the code? Grab it from the repo.</p>
	</div>

	<div class="callout callout__content callout_get_code">
		<i class="material-icons">
			video_library
		</i>
		<p>Watch the tutorial video on YouTube</p>
	</div>
</section>

<section class="tutorial-body">

	<hr>

	<h2 id="{{ step_one.article_headers[0].link }}">1.0.0 {{ step_one.article_headers[0].header }}</h2>

	<div class="micro-step">
		<strong>1.0.1</strong>
		<p>Set up your working directory</p>
		<code>$ mkdir json-project && cd json-project</code>
	</div>

	<div class="micro-step">
		<strong>1.0.2</strong>
		<p>Create a new file</p>
		<code>$ touch app.py data.json</code>
	</div>

	<div class="micro-step">
		<strong>1.0.3</strong>
		<p>In this tutorial we are going to import JSON from a file on out root directory. Save it as <var>data.json</var>.</p>
		<code>
            {<br/>
            &#8195;"title": "Working with JSON",<br/>
            &#8195;"category_type": "one-shot",<br/>
            &#8195;"objective_paragraph": "to use JavaScript Object Notation ( JSON ) to populate rubric elements of articles&#8195;",<br/>
            &#8195;"chapters": [<br/>
            &#8195;&#8195;{<br/>
            &#8195;&#8195;&#8195;"number": "One",<br/>
            &#8195;&#8195;&#8195;"teaser": "Set up the project archetechture and functions to accept JSON as data and populate the view template with such data.",<br/>
            &#8195;&#8195;&#8195;"chapter_link": "article_02_chapter_01"<br/>
            &#8195;&#8195;}<br/>
            &#8195;]<br/>
            }<br/>
        </code>
	</div>

	<p>Having both files in the same directory will give you the following structure</p>
	<code>
        json-project<br />
		&boxvr; app.py<br/>
		&boxvr; data.json<br/>
		&boxur; index.html
    </code>


	<p class="util-margin-top-30">This completes our project folder.</p>

	<hr />

	<h2 id="{{ step_one.article_headers[1].link }}">2.0.0 {{ step_one.article_headers[1].header }}</h2>

	<!-- 
		A11y Forms
		POST, GET methods
		HTML Forms
			input
				name, id, label, value
			button
				submit

		import the request module
		request methods
			form = get from POST method
			arg  = get from GET method
		
		import json
		json methods
			open("FILENAME", "w") write mode
			loads(), dumps()
			There has to be a better way to break down the form than listing all the fields

		Form Schema
			input:  string, firstName
			input:  string, lastName
			input:  number, age
			select: string, dayOfBirth

		* How to mask fields
			- phone number
			- dates
		
		* How to show children based on selection
		
		* Add multiple multiple children to parent object
			nested two levels
	 -->

	<form action="{{ url_for('article_03_chapter_01') }}" method="POST" class="util-margin-bottom-30">

		<label for="first_name">First name:</label>
		<input type="text" id="first_name" name="first_name">

		<label for="last_name" class="util-margin-top-25">Last name:</label>
		<input type="text" id="last_name" name="last_name">

		<label for="age" class="util-margin-top-25">Age ( days ):</label>
		<input type="number" id="age" name="age">

		<label for="day_born" class="util-margin-top-25">What day where you born?</label>
		<select id="day_born" name="day_born">
			<option>-- select day --</option>
			<option value="monday">Monday</option>
			<option value="tuesday">Tuesday</option>
			<option value="wednesday">Wednesday</option>
			<option value="thrusday">Thrusday</option>
			<option value="friday">Friday</option>
			<option value="saturday">Saturday</option>
			<option value="sunday">Sunday</option>
		</select>

		<div class="util-margin-top-30">
			<button type="submit">Submit</button>
		</div>
	</form>

	<hr />

	<h2 id="conclusion">Conclusion</h2>
	<p>There's three ( 3 ) simple steps to importing JSON into your template. Import it, unpack it, call it. But that's not all the uses for it. In other articles I write about how we can save form data as JSON, how we can make desitions based on key-value pairs in the back-end as well and the front-end, and how we can graph JSON on the browser. It's popularity is because it flexability and it's implamentations are only based one's imagination.</p>

	<section class="callout-section">
		<div class="callout callout__content callout_get_code">
			<i class="material-icons">
				code
			</i>
			<p>Need the code? Grab it from the repo.</p>
		</div>

		<div class="callout callout__content callout_get_code">
			<i class="material-icons">
				video_library
			</i>
			<p>Watch the tutorial video on YouTube</p>
		</div>
	</section>

</section>
</hr>
{% endblock %}

app/templates/article-03/resource.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for( navigation.welcome_link ) }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( chapters[0].chapter_link ) }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( navigation.resource_link ) }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<h1 class="h2">Links used to create this article</h1>
<ol>
	<li>
		<a href="https://scotch.io/bar-talk/processing-incoming-request-data-in-flask" target="_blank">https://scotch.io/bar-talk/processing-incoming-request-data-in-flask</a>
	</li>
	<li>
		<a href="https://www.youtube.com/watch?v=zdgYw-3tzfI&list=WL&index=11&t=3489s" target="_blank">https://www.youtube.com/watch?v=zdgYw-3tzfI&list=WL&index=11&t=3489s</a>
	</li>
	<li>
		<a href="https://stackoverflow.com/questions/10434599/get-the-data-received-in-a-flask-request" target="_blank">https://stackoverflow.com/questions/10434599/get-the-data-received-in-a-flask-request</a>
	</li>
	<li>
		<a href="https://www.programiz.com/python-programming/type-conversion-and-casting" target="_blank">https://www.programiz.com/python-programming/type-conversion-and-casting</a>
	</li>
	<li>
		<a href="http://blog.luisrei.com/articles/flaskrest.html" target="_blank">http://blog.luisrei.com/articles/flaskrest.html</a>
	</li>
	<li>
		<a href="https://web.itu.edu.tr/uyar/fad/forms.html" target="_blank">https://web.itu.edu.tr/uyar/fad/forms.html</a>
	</li>
	<li>
		<a href="https://pythonspot.com/flask-web-forms/" target="_blank">https://pythonspot.com/flask-web-forms/</a>
	</li>
	<li>
		<a href="https://www.twilio.com/blog/a-phone-number-input-field-for-flask-forms" target="_blank">https://www.twilio.com/blog/a-phone-number-input-field-for-flask-forms</a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
	<li>
		<a href="" target="_blank"></a>
	</li>
</ol>
{% endblock %}

app/templates/article-03/working-form.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for( navigation.welcome_link ) }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( chapters[0].chapter_link ) }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for( navigation.resource_link ) }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<section class="tutorial-body">

	<form action="{{ url_for('article_03_chapter_01') }}" method="POST" class="util-margin-bottom-30">

		<fieldset>
			<legend>Parent information:</legend>
			<label for="first_name">First name:</label>
			<input type="text" id="first_name" name="first_name">

			<label for="last_name" class="util-margin-top-25">Last name:</label>
			<input type="text" id="last_name" name="last_name">

			<label for="phone_number" class="util-margin-top-25">Phone number:</label>
			<input type="tel" id="phone_number" name="phone_number">
		</fieldset>

		<fieldset class="util-margin-top-40">
			<legend>Child information:</legend>
			<label for="first_name">First name:</label>
			<input type="text" id="first_name" name="first_name">

			<label for="last_name" class="util-margin-top-25">Last name:</label>
			<input type="text" id="last_name" name="last_name">

			<label for="birthday" class="util-margin-top-25">Birthday:</label>
			<input type="number" id="birthday" name="birthday">
		</fieldset>

		<input type="file" id="upload-file" name="file" />

		<div class="util-margin-top-30">
			<button type="submit">Submit</button>
		</div>
	</form>

	<hr />

	<h2 id="conclusion">Conclusion</h2>
	<p>There's three ( 3 ) simple steps to importing JSON into your template. Import it, unpack it, call it. But that's not all the uses for it. In other articles I write about how we can save form data as JSON, how we can make desitions based on key-value pairs in the back-end as well and the front-end, and how we can graph JSON on the browser. It's popularity is because it flexability and it's implamentations are only based one's imagination.</p>

	<section class="callout-section">
		<div class="callout callout__content callout_get_code">
			<i class="material-icons">
				code
			</i>
			<p>Need the code? Grab it from the repo.</p>
		</div>

		<div class="callout callout__content callout_get_code">
			<i class="material-icons">
				video_library
			</i>
			<p>Watch the tutorial video on YouTube</p>
		</div>
	</section>

</section>
</hr>
{% endblock %}

app/templates/website/appendix.html
{% extends "templates/website-template.html" %}

{% block content %}
<section>
	<table>
		<tr>
			<th>Scale Category</th>
			<th>Typeface</td>
			<th>Font</td>
			<th>Font Weight</td>
			<th>Size</td>
			<th>Case</td>
			<th>Letter Spacing</th>
			<th>Line Height</th>
			<th>Padding</th>
			<th>Margin</th>
		</tr>
		<tr>
			<td class="h1">H1</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="h2">H2</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="h3">H3</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="h4">H4</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="h5">H5</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="h6">H6</td>
			<td>Roboto</td>
			<td>Slab</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Subtitle1</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Bold - 700</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Subtitle2</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Body1</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Body2</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Button</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td>Caption</td>
			<td>Roboto</td>
			<td>Mono</td>
			<td>Regular - 400</td>
			<td>100rem</td>
			<td>Sentence</td>
			<td>-1.5</td>
		</tr>
		<tr>
			<td class="overline">Overline</td>
			<td>Roboto</td>
			<td>Regular</td>
			<td>Regular - 400</td>
			<td>1.2rem</td>
			<td>All Caps</td>
			<td>1.5px</td>
		</tr>
	</table>
</section>
{% endblock %}

app/templates/website/index.html
{% extends "templates/website-template.html" %}

{% block page %}
<div class="body__container article__container">
	<div class="card card--course util-margin-top-30">
		<div class="card__title">
			<div class="card__title--main">Article 01</div>
		</div>

		<div class="card__content">
			<p>Write a web scraper that creates a YouTube playlist based on songs in your Shazam library.</p>
		</div>

		<div class="card__button">
			<a class="button" href="{{ url_for('article_01.welcome') }}">go to article</a>
		</div>
	</div>

	<div class="card--course__connector">
		<div></div>
		<div></div>
	</div>

	<div class="card card--course">
		<div class="card__title">
			<div class="card__title--main">Article 02</div>
		</div>

		<div class="card__content">
			<p>Populate article content with JSON</p>
		</div>

		<div class="card__button">
			<a class="button" href="{{ url_for('article_02.welcome') }}">go to article</a>
		</div>
	</div>

	<div class="card--course__connector">
		<div></div>
		<div></div>
	</div>

	<div class="card card--course">
		<div class="card__title">
			<div class="card__title--main">Article 03</div>
		</div>

		<div class="card__content">
			<p>Upload files in Flask</p>
		</div>

		<div class="card__button">
			<a class="button" href="{{ url_for('article_03.welcome') }}">go to article</a>
		</div>
	</div>
</div>
{% endblock %}