app/article_03/models.py
import os

from flask import request, redirect
from app import app


def allowed_file_types(filename):
    if not "." in filename:
        return False

    extension = filename.rsplit(".", 1)[1]

    if extension.upper() in app.config["ALLOWED_IMAGE_EXTENSIONS"]:
        return True
    else:
        return False


def upload_file(uploaded_file):
	uploaded_file = uploaded_file

	if uploaded_file.filename == "":
		print("No filename")
		return redirect(request.url)
		
	if allowed_file_types(uploaded_file.filename):
		uploaded_file.save(os.path.join(app.config["UPLOAD_FILES"], uploaded_file.filename))
		return redirect(request.url)
	else:
		print("That file extension is not allowed")
		return redirect(request.url)

app/article_03/__init__.py
# No content
# We need this file just to make this folder a python module

app/article_03/views.py
from flask import render_template, Blueprint, request
from app import app

from app.article_03.models import *

article_03_blueprint = Blueprint("article_03", __name__, template_folder='templates')

@article_03_blueprint.route('/welcome')
def welcome():
	return render_template("/article-03/welcome.html")


@article_03_blueprint.route('/chapter-01', methods=["GET", "POST"])
def chapter_01():
	if request.method  == "POST":
		if request.files:
			upload_file(request.files["upload-form"])

	return render_template("/article-03/chapter-01.html")


@article_03_blueprint.route('/resource')
def resource():
	return render_template("/article-03/resource.html")

app/article_03/templates/article-03/chapter-01.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for('article_03.welcome') }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.chapter_01') }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.resource') }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<h1>Chapter 01 Page</h1>
<h1 class="h2">Upload Form</h1>
<form action="{{ url_for('article_03.chapter_01') }}" method="POST" enctype="multipart/form-data" class="util-margin-bottom-30">

	<label for="upload-form">Upload file</label>
	<input type="file" id="upload-form" name="upload-form">

	<button type="submit">Submit</button>
</form>
{% endblock %}

app/article_03/templates/article-03/file-uploaded.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for('article_03.welcome') }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.chapter_01') }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.resource') }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<h1>File uploaded successful</h1>
{% endblock %}

app/article_03/templates/article-03/resource.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for('article_03.welcome') }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.chapter_01') }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.resource') }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<h1>Resource Page</h1>
{% endblock %}

app/article_03/templates/article-03/welcome.html
{% extends "templates/article-template.html" %}

{% block navigation %}
{{super()}}
<section>
	<nav class="navigation util-margin-top-30">
		<ul class="navigation__menu-list">
			<li>
				<a href="{{ url_for('article_03.welcome') }}">
					<div class="navigation--title">welcome</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.chapter_01') }}">
					<div class="navigation--title">get started</div>
				</a>
			</li>
			<li>
				<a href="{{ url_for('article_03.resource') }}">
					<div class="navigation--title">resources</div>
				</a>
			</li>
		</ul>
	</nav>
</section>
{% endblock %}

{% block page %}
<section class="page-header">
	<h1>Uploading files with Flask</h1>

	<div class="overline">Category: one-shot</div>

	<p class="objective-paragraph">Welcome! The <strong>objective</strong> of this tutorial is to learn how to upload CSV files</p>
</section>

<div class="card card--course util-margin-top-30">
	<div class="card__title">
		<div class="card__title--main">Chapter 1</div>
	</div>

	<div class="card__content">
		<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non quae obcaecati sed quia a eveniet quidem placeat libero commodi facere consectetur deleniti mollitia alias reprehenderit cum accusamus eaque ducimus.</p>
	</div>

	<div class="card__button">
		<a class="button" href="{{ url_for('article_03.chapter_01') }}">go to chapter</a>
	</div>
</div>

<div class="card--course__connector">
	<div></div>
	<div></div>
</div>

<div class="card card--course card--course__success">
	<div class="card__title">
		<div class="card__title--main h1">Complete</div>
	</div>
</div>

<hr />
{% endblock %}