app/article_01/views.py
from flask import render_template, Blueprint


article_01_blueprint = Blueprint("article_01", __name__, template_folder='templates')


@article_01_blueprint.route('/welcome')
def welcome():
	return render_template("article_01/welcome.html")


@article_01_blueprint.route('/chapter-01')
def chapter_01():
	return render_template("article_01/chapter-01.html")


@article_01_blueprint.route('/resource')
def resource():
	return render_template("article_01/resource.html")

app/article_01/templates/article_01/resource.html
{% extends "templates/article-template.html" %}

{% block page %}
<h1>Resource</h1>

<div class="card util-margin-vert-60">
	<div class="card__title">
		<i class="material-icons md-36">sports</i>
		<div class="card__title--main">Quick Break</div>
	</div>
	<div class="card__content">
		<p>Be sure to update the .gitignore file from the repo</p>
	</div>
</div>

<div class="card util-margin-vert-60">
	<div class="card__title">
		<i class="material-icons md-36">image</i>
		<div class="card__title--main">Figure 1.0</div>
	</div>
	<div class="card__image">
		<img src="./images/hello-world.png" alt="python video">
	</div>
	<div class="card__content">
		<p>And you should see your basic "Hello world" app in action on
			<a href="http://localhost:5000/">http://localhost:5000/</a>.</p>
		<p>
			<span class="tooltipped tooltip" data-position="top" data-tooltip="In the terminal: Ctrl+C">Kill
				the server</span> when you're done.
		</p>
	</div>

	<div class="card__button">
		<button>button</button>
		<button>button</button>
	</div>
</div>


<div class="card util-margin-vert-60">
	<div class="card__title">
		<i class="material-icons md-36">image</i>
		<div class="card__title--main">Figure 2.0</div>
	</div>
	<div class="card__image">
		<img src="./images/hello-world.png" alt="python video">
	</div>
	<div class="card__content">
		<p><a href="http://localhost:5000/">http://localhost:5000/henry</a> will return "Hello Henry"
		</p>
	</div>
</div>

<h3 id="local-settings">3.1.0 Local Settings</h3>

<div class="sub-h6">Local:</div>
<code>
	$ python app.py<br/>
	config.DevelopmentConfig
</code>

<div class="sub-h6">Staging:</div>
<code>
	$ heroku run python app.py --app wordcount-stage<br/>
	Running python app.py on wordcount-stage... up, run.7699
	config.StagingConfig
</code>

<div class="sub-h6">Production:</div>
<code>
	$ heroku run python app.py --app wordcount-pro
	Running python app.py on wordcount-pro... up, run.8934
	config.ProductionConfig
</code>
{% endblock %}

app/article_01/templates/article_01/welcome.html
{% extends "templates/article-template.html" %}

{% block page %}
<section>
	<img src="https://images.unsplash.com/photo-1461711513774-c78b437a740b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=1600" alt="random picture">
</section>

<section class="page-header">
	<h1>Python Web Scraper</h1>
	<div class="overline">Category: Series</div>

	<p class="objective-paragraph">Welcome! The <strong>objective</strong> of this tutorial is to build web scraper that creates a YouTube playlist based on songs in your Shazam library</p>
</section>

<div class="card card--course util-margin-top-30">
	<div class="card__title">
		<div class="card__title--main">Chapter One</div>
	</div>
	<div class="card__content">
		<p>Set up project folder and write the code that crawls through your Shazam libray.</p>
	</div>

	<div class="card__button">
		<div class="button">
			<a href="{{ url_for('article_01.chapter_01') }}">go to chapter</a>
		</div>
	</div>
</div>

<div class="card--course__connector">
	<div></div>
	<div></div>
</div>

<div class="card card--course">
	<div class="card__title">
		<div class="card__title--main">Chapter Two</div>
	</div>
	<div class="card__content">
		<p>Set your YouTube account to accept incoming data and create or add songs to a specified playlist.</p>
	</div>
	<div class="card__button">
		<div class="button">
			<a href="#">go to chapter</a>
		</div>
	</div>
</div>

<div class="card--course__connector">
	<div></div>
	<div></div>
</div>

<div class="card card--course card--course__success">
	<div class="card__title">
		<div class="card__title--main h1">Complete</div>
	</div>
</div>

<hr />
<h2 id="conclusion">Course Updates</h2>
<table class="util-margin-bottom-60">
	<tr>
		<th>Date</th>
		<th>Description</th>
	</tr>
	<tr>
		<td>03/22/2016</td>
		<td>
			<ul>
				<li>Upgraded to Python version 3.5.1</li>
				<li>Added autoenv version 1.0.0</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td>02/22/2015</td>
		<td>Added Python 3 support</td>
	</tr>
</table>
{% endblock %}